server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    secret: kpwang@Login(Auth}*^31)&niubi% # 登录校验的密钥
    pubKeyPath: F:\\rsa\\rsa.pub # 公钥地址
    priKeyPath: F:\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN