server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.154.129:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.154.128
  rabbitmq:
    host: 192.168.154.135
    virtual-host: /leyou
    username: kpwang
    password: ww920321
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo