server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.154.128:33306/mybatis?characterEncoding=utf-8
    username: root
    password: root
  application:
    name: service-provider
mybatis:
  type-aliases-package: cn.itcast.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka


